# config/routes/nelmio_api_doc.yaml
# Les routes sont maintenant gérées par SwaggerController
# app.swagger_ui:
#     path: /api/doc
#     methods: GET
#     defaults: { _controller: Nelmio\ApiDocBundle\Controller\SwaggerUiController::__invoke }

# app.swagger:
#     path: /api/doc.json
#     methods: GET
#     defaults: { _controller: Nelmio\ApiDocBundle\Controller\DocumentationController::__invoke } 